from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from datetime import datetime


def generate_report(emergency_data):

    report = {

        "Emergency Type":
        emergency_data["type"],

        "Priority Level":
        emergency_data["severity"],

        "Confidence Score":
        f'{emergency_data["confidence"]}%',

        "Required Support":
        emergency_data["required_help"],

        "Generated Date":
        datetime.now().strftime("%d-%m-%Y"),

        "Recommended Response":
        "Move to a safe location and connect with available emergency support."

    }


    return report





def create_pdf(report):

    file_name = "HopeLink_Emergency_Report.pdf"


    pdf = canvas.Canvas(
        file_name,
        pagesize=letter
    )


    width, height = letter


    y = height - 70



    # Title

    pdf.setFont(
        "Helvetica-Bold",
        18
    )


    pdf.drawCentredString(
        width/2,
        y,
        "HopeLink AI Emergency Report"
    )


    y -= 50



    pdf.setFont(
        "Helvetica",
        12
    )


    for key, value in report.items():


        if y < 80:

            pdf.showPage()

            y = height - 70



        pdf.setFont(
            "Helvetica-Bold",
            12
        )


        pdf.drawString(
            80,
            y,
            key + ":"
        )


        y -= 20


        pdf.setFont(
            "Helvetica",
            12
        )


        if isinstance(value, list):


            for item in value:

                pdf.drawString(
                    100,
                    y,
                    "• " + item
                )

                y -= 18


        else:


            pdf.drawString(
                100,
                y,
                str(value)
            )

            y -= 18



        y -= 15



    # Footer

    pdf.setFont(
        "Helvetica-Oblique",
        9
    )


    pdf.drawCentredString(
        width/2,
        40,
        "Generated by HopeLink AI Emergency Response System"
    )


    pdf.save()


    return file_name